name: Code Snippet
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          filename: code-snippet.svg
          
          plugin_code: yes
          plugin_code_lines: 100
          plugin_code_load: 1000
          plugin_code_visibility: public
