name: GitHub Metrics
on:
  # Schedule updates
  schedule: 
    - cron: "0 * * * *"
  push: 
    branches: master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
          
          plugin_traffic: yes
          
          #plugin_isocalendar: yes
          
          #plugin_music: yes
          #plugin_music_provider: spotify
          #plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          #plugin_music_mode: recent
          #plugin_music_limit: 5
          
          plugin_projects: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_ignored: tsx
          plugin_languages_limit: 8
          commits_authoring: matievisthekat@gmail.com
          
          #plugin_stackoverflow: yes
          #plugin_stackoverflow_user: 12493413
          #plugin_stackoverflow_sections: answers-top
          #plugin_stackoverflow_limit: 2
          #plugin_stackoverflow_lines: 4
          
          plugin_followup: yes
          plugin_followup_sections: user
          
          #plugin_achievements: yes
          #plugin_achievements_secrets: yes
          #plugin_achievements_limit: 5
          #plugin_achievements_display: detailed
          
          plugin_lines: yes
          
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 60
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
          #plugin_wakatime: yes
          #plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          #plugin_wakatime_days: 7
          #plugin_wakatime_sections: time
          #plugin_wakatime_limit: 4
