name: GitHub Metrics
on:
  # Schedule updates
  schedule: 
    - cron: "0 * * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
          
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_ignored: tsx
          plugin_languages_limit: 8
          commits_authoring: matievisthekat@gmail.com
          
          plugin_followup: yes
          plugin_followup_sections: user
          
          plugin_lines: yes
          
          plugin_habits: yes
          plugin_habits_from: 500
          plugin_habits_days: 60
          plugin_habits_facts: no
          plugin_habits_charts: yes
