name: Movies
on:
  schedule: 
    - cron: "0 0 * * *"
jobs:
  movies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: "14"
    - run: cd movies
    - run: yarn
    - run: node .
