name: Overall Language Metrics
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/overall-langauges.yml
  schedule: 
    - cron: "0 0 * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: no
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          filename: overall-languages.svg
          
          plugin_traffic: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          plugin_languages_categories: programming
          plugin_languages_ignored: tsx, css
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          commits_authoring: matievisthekat@gmail.com
