name: Overall Metrics
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          filename: overall-metrics.svg
          
          plugin_traffic: yes
          
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_limit: 5
          plugin_music_top_type: artists
          plugin_music_time_range: medium
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          
          plugin_languages: yes
          plugin_languages_details: byte-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          plugin_languages_ignored: tsx, css
          plugin_languages_aliases: RenderScript:Rust # temp solution until Rust as RenderScript bug is fixed
          commits_authoring: matievisthekat@gmail.com
          
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_lines: yes
          
          plugin_poopmap: yes
          plugin_poopmap_token: "15d71a6dc6682c75553ab48c2db4edc4"
          plugin_poopmap_days: 180
