name: Recent Metrics
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          
          plugin_languages: yes
          plugin_languages_details: lines
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          plugin_languages_ignored: tsx
          plugin_languages_limit: 6
          commits_authoring: matievisthekat@gmail.com
          
          plugin_code: yes
          plugin_code_lines: 30               # Only display snippets with less than 12 lines
          plugin_code_load: 1000              # Fetch 100 events from activity
          plugin_code_visibility: public      # Only display snippets from public activity
          
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 60
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, editors, os
