name: Recent Metrics
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/recent-metrics.yml
  schedule: 
    - cron: "0 * * * *"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Africa/Johannesburg
          config_padding: 0, 0
          filename: recent-metrics.svg
          
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, editors, os
          
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
