name: Wakatime Metrics
on:
  # Schedule updates
  schedule:
    - cron: "0 * * * *"
  push: 
    branches: master
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.WAKA_METRICS_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROJECTS: "False"
